##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
#
# @section DESCRIPTION
# Collects sources for a build.
##
Import('env')

# gather sources
l_sources = [ 'solvers/roe/Roe.cpp',
              'solvers/f-Wave/F_wave.cpp',
              'patches/WavePropagation1d.cpp',
              'setups/DamBreak1d.cpp',
              'io/Csv.cpp' ]

for l_so in l_sources:
  env.sources.append( env.Object( l_so ) )

env.standalone = env.Object( "main.cpp" )

# gather unit tests
l_tests = [ 'tests.cpp',
            'solvers/roe/Roe.test.cpp',
            'solvers/f-Wave/F_wave.test.cpp',
            'patches/WavePropagation1d.test.cpp',
            'io/Csv.test.cpp',
            'setups/DamBreak1d.test.cpp' ]

for l_te in l_tests:
  env.tests.append( env.Object( l_te ) )

Export('env')