##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
#
# @section DESCRIPTION
# Collects sources for a build.
##
Import('env')

# gather sources
l_sources = [ 'solvers/Roe.cpp',
              'solvers/FWave.cpp',
              'patches/WavePropagation1d.cpp',
              'setups/CustomSetup1d/CustomSetup1d.cpp',
              'setups/DamBreak1d/DamBreak1d.cpp',
              'setups/RareRare1d/RareRare1d.cpp',
              'setups/ShockShock1d/ShockShock1d.cpp',
              'setups/SubcriticalFlow1d/SubcriticalFlow1d.cpp',
              'setups/SupercriticalFlow1d/SupercriticalFlow1d.cpp',
              'configs/SimConfig.cpp',
              'io/Csv/Csv.cpp',
              'io/JsonParameterReader/JsonParameterReader.cpp']

for l_so in l_sources:
  env.sources.append( env.Object( l_so ) )

env.standalone = env.Object( "main.cpp" )

# gather unit tests
l_tests = [ 'tests.cpp',
            'solvers/Roe.test.cpp',
            'solvers/FWave.test.cpp',
            'patches/WavePropagation1d.test.cpp',
            'setups/CustomSetup1d/CustomSetup1d.test.cpp',
            'setups/DamBreak1d/DamBreak1d.test.cpp',
            'setups/ShockShock1d/ShockShock1d.test.cpp',
            'setups/RareRare1d/RareRare1d.test.cpp',
            'setups/SubcriticalFlow1d/SubcriticalFlow1d.test.cpp',
            'setups/SupercriticalFlow1d/SupercriticalFlow1d.test.cpp',
            'configs/SimConfig.test.cpp',
            'io/Csv/Csv.test.cpp',
            'io/JsonParameterReader/JsonParameterReader.test.cpp']

for l_te in l_tests:
  env.tests.append( env.Object( l_te ) )

Export('env')
