name: Docs

on:
  #push:
  #  branches-ignore:
  #    - '**'
  workflow_dispatch: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Requirements
      run: sudo apt-get install doxygen
        && pip3 install sphinx
        && pip3 install sphinx-rtd-theme
        && pip3 install breathe
        && pip3 install sphinx-copybutton
    - name: Checkout repo
      uses: actions/checkout@v4.1.0
    - name: Build docs
      run: cd docs_sphinx
        && make html
        && cd _build/html
        && touch .nojekyll
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        folder: docs_sphinx/_build/html # The folder the action should deploy.